apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  annotations:
    eventing.knative.dev/creator: kn-connectors
  labels:
    eventing.knative.dev/connector: split-transformer
    eventing.knative.dev/broker: default
  name: split-transformer
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: split-transformer
