apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    eventing.knative.dev/connector: aws-sqs-source
  name: kn-connector-aws-sqs-source
spec:
  selector:
    matchLabels:
      eventing.knative.dev/connector: aws-sqs-source
  template:
    metadata:
      labels:
        eventing.knative.dev/connector: aws-sqs-source
    spec:
      containers:
      - name: kn-connector-aws-sqs-source
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  annotations:
    sources.knative.dev/creator: connectors.knative.dev
  finalizers:
    - sinkbindings.sources.knative.dev
  labels:
    eventing.knative.dev/connector: aws-sqs-source
  name: kn-connector-aws-sqs-source
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
  subject:
    apiVersion: apps/v1
    kind: Deployment
    name: kn-connector-aws-sqs-source
