apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  annotations:
    eventing.knative.dev/creator: kn-connectors
  labels:
    eventing.knative.dev/connector: ${kamelet-name}-sink
    eventing.knative.dev/broker: default
  name: ${kamelet-name}-sink
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: ${kamelet-name}-sink
